"""Database utility helpers shared across route modules."""

import re

import sqlalchemy as sa
from sqlalchemy.ext.asyncio import AsyncSession

_SIMPLE_IDENTIFIER_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _quote_qualified_identifier(name: str) -> str:
    """Return a safely quoted table/sequence identifier (optionally schema-qualified)."""
    parts = name.split(".")
    if len(parts) not in (1, 2) or not all(_SIMPLE_IDENTIFIER_RE.fullmatch(p) for p in parts):
        raise ValueError(
            f"Invalid SQL identifier '{name}'. Use unquoted names like 'users' or 'public.users'."
        )
    return ".".join(f'"{part}"' for part in parts)


async def reset_sequence_to_min_gap(
    db: AsyncSession,
    table: str,
    seq: str,
) -> None:
    """Reset a PostgreSQL sequence so the next insert reuses the lowest free ID.

    After deleting a row, call this to find the first gap in 1…MAX(id) and set
    the sequence to (gap - 1), so ``nextval`` returns that freed ID on the next
    insert.

    If no gap exists (IDs are contiguous), the sequence is set so the next
    insert uses ``MAX(id) + 1``.
    If the table is empty, the next insert gets ID 1.

    Internally this uses ``setval(seq, next_id, false)`` so PostgreSQL returns
    exactly ``next_id`` on the next ``nextval`` call.

    Safety notes:
    - table/sequence identifiers are validated against a strict allow-list pattern
    - table and sequence existence are verified via ``to_regclass``
    - raises an error if table or sequence does not exist

    Parameters
    ----------
    db : AsyncSession
        The active SQLAlchemy async session.
    table : str
        Unquoted table name (e.g. ``"users"``).
    seq : str
        PostgreSQL sequence name (e.g. ``"users_id_seq"``).  For a column
        defined as ``SERIAL`` or ``GENERATED BY DEFAULT AS IDENTITY``, this is
        typically ``<table>_<column>_seq``.
    """
    table_ref = _quote_qualified_identifier(table)
    seq_ref = _quote_qualified_identifier(seq)

    table_exists = await db.scalar(sa.text("SELECT to_regclass(:name)"), {"name": table})
    if table_exists is None:
        raise ValueError(f"Table '{table}' does not exist")

    seq_exists = await db.scalar(sa.text("SELECT to_regclass(:name)"), {"name": seq})
    if seq_exists is None:
        raise ValueError(f"Sequence '{seq}' does not exist")

    await db.execute(
        sa.text(
            f"""
            WITH stats AS (
                SELECT MIN(id) AS min_id, MAX(id) AS max_id
                FROM {table_ref}
            ),
            ordered AS (
                SELECT
                    id,
                    LAG(id) OVER (ORDER BY id) AS prev_id
                FROM {table_ref}
            ),
            gap AS (
                -- First internal gap: ..., n, n+2, ...
                SELECT (prev_id + 1) AS next_id
                FROM ordered
                WHERE prev_id IS NOT NULL AND id > prev_id + 1
                ORDER BY prev_id
                LIMIT 1
            ),
            target AS (
                SELECT CASE
                    WHEN (SELECT min_id FROM stats) IS NULL THEN 1
                    WHEN (SELECT min_id FROM stats) > 1 THEN 1
                    ELSE COALESCE(
                        (SELECT next_id FROM gap),
                        (SELECT max_id + 1 FROM stats)
                    )
                END AS next_id
            )
            SELECT setval('{seq_ref}'::regclass, (SELECT next_id FROM target), false)
            """
        )
    )
