"""Database utility helpers shared across route modules."""

import re

import sqlalchemy as sa
import logging
from sqlalchemy.ext.asyncio import AsyncSession

logger = logging.getLogger("yolohome")

_SIMPLE_IDENTIFIER_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _quote_qualified_identifier(name: str) -> str:
    """Return a safely quoted table/sequence identifier (optionally schema-qualified)."""
    parts = name.split(".")
    if len(parts) not in (1, 2) or not all(_SIMPLE_IDENTIFIER_RE.fullmatch(p) for p in parts):
        raise ValueError(
            f"Invalid SQL identifier '{name}'. Use unquoted names like 'users' or 'public.users'."
        )
    return ".".join(f'"{part}"' for part in parts)


async def reset_sequence_to_min_gap(
    db: AsyncSession,
    table: str,
    seq: str,
) -> None:
    """Reset a PostgreSQL sequence so the next insert reuses the lowest free ID.

    After deleting a row, call this to find the first gap in 1…MAX(id) and set
    the sequence to (gap - 1), so ``nextval`` returns that freed ID on the next
    insert.

    If no gap exists (IDs are contiguous), the sequence is set so the next
    insert uses ``MAX(id) + 1``.
    If the table is empty, the next insert gets ID 1.

    Internally this uses ``setval(seq, next_id, false)`` so PostgreSQL returns
    exactly ``next_id`` on the next ``nextval`` call.

    Safety notes:
    - table/sequence identifiers are validated against a strict allow-list pattern
    - table and sequence existence are verified via ``to_regclass``
    - raises an error if table or sequence does not exist

    Parameters
    ----------
    db : AsyncSession
        The active SQLAlchemy async session.
    table : str
        Unquoted table name (e.g. ``"users"``).
    seq : str
        PostgreSQL sequence name (e.g. ``"users_id_seq"``).  For a column
        defined as ``SERIAL`` or ``GENERATED BY DEFAULT AS IDENTITY``, this is
        typically ``<table>_<column>_seq``.
    """
    table_ref = _quote_qualified_identifier(table)
    seq_ref = _quote_qualified_identifier(seq)

    table_exists = await db.scalar(sa.text("SELECT to_regclass(:name)"), {"name": table})
    if table_exists is None:
        raise ValueError(f"Table '{table}' does not exist")

    seq_exists = await db.scalar(sa.text("SELECT to_regclass(:name)"), {"name": seq})
    if seq_exists is None:
        raise ValueError(f"Sequence '{seq}' does not exist")

    await db.execute(
        sa.text(
            f"""WITH stats AS (
            SELECT 
                COALESCE(MIN(id), 0) AS min_id,
                COALESCE(MAX(id), 0) AS max_id
            FROM {table_ref}
            )
            SELECT setval(
                '{seq_ref}'::regclass,
                CASE
                    WHEN stats.min_id = 0 OR stats.min_id > 1 THEN 1
                    ELSE COALESCE(
                        (SELECT id + 1 
                        FROM {table_ref} t1
                        WHERE NOT EXISTS (SELECT 1 FROM {table_ref} t2 WHERE t2.id = t1.id + 1)
                        ORDER BY id 
                        LIMIT 1),
                        stats.max_id + 1
                    )
                END,
                false
            )
            FROM stats;
            """
        )
    )

async def handle_admin_reset(db: AsyncSession) -> None:
    """Permanently delete all admin accounts if ADMIN_RESET_MODE is enabled.
    
    This provides a 'fail-safe' or 'factory reset' for admin access.
    """
    from app.models.user import User
    from app.core.config import settings

    if not settings.ADMIN_RESET_MODE:
        return

    logger.warning("!!! [RESCUE] Chế độ ADMIN_RESET_MODE đang BẬT. Đang xóa các tài khoản admin cũ...")
    
    # Delete all admins
    result = await db.execute(sa.delete(User).where(User.role == "admin"))
    deleted_count = result.rowcount
    
    await db.commit()
    
    if deleted_count > 0:
        logger.info(f"!!! [RESCUE] Đã xóa thành công {deleted_count} tài khoản admin. Hệ thống đã sẵn sàng để đăng ký lại.")
    else:
        logger.info("!!! [RESCUE] Không tìm thấy tài khoản admin nào để xóa. Hệ thống đã sẵn sàng để đăng ký lại.")
