"""Database utility helpers shared across route modules."""

import sqlalchemy as sa
from sqlalchemy.ext.asyncio import AsyncSession


async def reset_sequence_to_min_gap(
    db: AsyncSession,
    table: str,
    seq: str,
) -> None:
    """Reset a PostgreSQL SERIAL sequence so the next insert reuses the lowest free ID.

    After deleting a row, call this to find the first gap in 1…MAX(id) and set
    the sequence to (gap - 1), so ``nextval`` returns that freed ID on the next
    insert.

    If no gap exists (IDs are contiguous), the sequence is set so the next
    insert uses ``MAX(id) + 1``.
    If the table is empty, the next insert gets ID 1.

    Internally this uses ``setval(seq, next_id, false)`` so PostgreSQL returns
    exactly ``next_id`` on the next ``nextval`` call. This avoids invalid
    ``setval(..., 0)`` errors when the first reusable ID is 1.

    Parameters
    ----------
    db : AsyncSession
        The active SQLAlchemy async session.
    table : str
        Unquoted table name (e.g. ``"users"``).
    seq : str
        PostgreSQL sequence name (e.g. ``"users_id_seq"``).  For a column
        defined as ``SERIAL`` or ``GENERATED BY DEFAULT AS IDENTITY``, this is
        typically ``<table>_<column>_seq``.
    """
    await db.execute(
        sa.text(
            f"""
            WITH stats AS (
                SELECT COALESCE(MAX(id), 0) AS max_id
                FROM {table}
            ),
            gap AS (
                -- Lowest missing ID in [1..MAX]
                SELECT MIN(s.id) AS next_id
                FROM generate_series(1, (SELECT max_id FROM stats)) AS s(id)
                WHERE NOT EXISTS (
                    SELECT 1
                    FROM {table} t
                    WHERE t.id = s.id
                )
            ),
            target AS (
                SELECT COALESCE(
                    (SELECT next_id FROM gap),
                    (SELECT max_id + 1 FROM stats)
                ) AS next_id
            )
            SELECT setval('{seq}', (SELECT next_id FROM target), false)
            """
        )
    )
