"""bo sung lai devicelog

Revision ID: 2fca50c19a47
Revises: c7577f5b5776
Create Date: 2026-04-23 17:52:30.954977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fca50c19a47'
down_revision: Union[str, Sequence[str], None] = 'c7577f5b5776'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('device_name', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_logs_created_at'), 'device_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_device_logs_id'), 'device_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_logs_id'), table_name='device_logs')
    op.drop_index(op.f('ix_device_logs_created_at'), table_name='device_logs')
    op.drop_table('device_logs')
    # ### end Alembic commands ###
