"""cap nhat bang device

Revision ID: 37ef4b08b6fb
Revises: 2fca50c19a47
Create Date: 2026-04-27 01:58:12.528839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37ef4b08b6fb'
down_revision: Union[str, Sequence[str], None] = '2fca50c19a47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('devices', 'type',
               existing_type=postgresql.ENUM('fan', 'light', 'camera', 'lock', 'temp_sensor', 'humidity_sensor', name='device_type_enum'),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('devices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint('_hardware_pin_uc', 'devices', ['hardware_id', 'pin'])
    op.create_index(op.f('ix_devices_created_at'), 'devices', ['created_at'], unique=False)
    op.alter_column('hardware_nodes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_hardware_nodes_created_at'), 'hardware_nodes', ['created_at'], unique=False)
    op.alter_column('sensor_data', 'sensor_type',
               existing_type=postgresql.ENUM('fan', 'light', 'camera', 'lock', 'temp_sensor', 'humidity_sensor', name='sensor_type_enum'),
               type_=sa.String(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sensor_data', 'sensor_type',
               existing_type=sa.String(length=32),
               type_=postgresql.ENUM('fan', 'light', 'camera', 'lock', 'temp_sensor', 'humidity_sensor', name='sensor_type_enum'),
               existing_nullable=False)
    op.drop_index(op.f('ix_hardware_nodes_created_at'), table_name='hardware_nodes')
    op.alter_column('hardware_nodes', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_devices_created_at'), table_name='devices')
    op.drop_constraint('_hardware_pin_uc', 'devices', type_='unique')
    op.alter_column('devices', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('devices', 'type',
               existing_type=sa.String(length=32),
               type_=postgresql.ENUM('fan', 'light', 'camera', 'lock', 'temp_sensor', 'humidity_sensor', name='device_type_enum'),
               existing_nullable=True)
    # ### end Alembic commands ###
