"""init_db

Revision ID: a1d9401a5669
Revises: 
Create Date: 2026-04-10 05:57:09.694333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'a1d9401a5669'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=32), server_default='user', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('dashboards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboards_id'), 'dashboards', ['id'], unique=False)
    op.create_index(op.f('ix_dashboards_owner_id'), 'dashboards', ['owner_id'], unique=False)
    op.create_table('hardware_nodes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('pins', sa.JSON(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invitation_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.Text(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dashboard_widgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dashboard_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('widget_type', sa.String(length=64), nullable=False),
    sa.Column('position_x', sa.Integer(), server_default='0', nullable=False),
    sa.Column('position_y', sa.Integer(), server_default='0', nullable=False),
    sa.Column('width', sa.Integer(), server_default='4', nullable=False),
    sa.Column('height', sa.Integer(), server_default='3', nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_widgets_dashboard_id'), 'dashboard_widgets', ['dashboard_id'], unique=False)
    op.create_index(op.f('ix_dashboard_widgets_id'), 'dashboard_widgets', ['id'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.Enum('fan', 'light', 'camera', 'lock', 'temp_sensor', 'humidity_sensor', 'unknown', name='device_type_enum'), nullable=True),
    sa.Column('isOn', sa.Boolean(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('room', sa.String(length=128), nullable=True),
    sa.Column('createdBy', sa.String(length=128), nullable=True),
    sa.Column('pin', sa.String(length=32), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduledOnTime', sa.String(length=32), nullable=True),
    sa.Column('scheduledOffTime', sa.String(length=32), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('search_keywords', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('hardwareId', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['hardwareId'], ['hardware_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_search_keywords'), 'devices', ['search_keywords'], unique=False)
    op.create_index(op.f('ix_devices_type'), 'devices', ['type'], unique=False)
    op.create_table('device_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('device_name', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_logs_created_at'), 'device_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_device_logs_id'), 'device_logs', ['id'], unique=False)
    op.create_table('device_schedules',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('time_of_day', sa.Time(), nullable=False),
    sa.Column('action', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_triggered_on', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_schedules_device_id'), 'device_schedules', ['device_id'], unique=False)
    op.create_table('device_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('face_enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feature_vector', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False),
    sa.Column('image_path', sa.String(length=512), nullable=True),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_face_enrollments_device_id'), 'face_enrollments', ['device_id'], unique=False)
    op.create_index(op.f('ix_face_enrollments_id'), 'face_enrollments', ['id'], unique=False)
    op.create_index(op.f('ix_face_enrollments_user_id'), 'face_enrollments', ['user_id'], unique=False)
    op.create_table('face_recognition_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('image_path', sa.String(length=512), nullable=True),
    sa.Column('matched_enrollment_id', sa.Integer(), nullable=True),
    sa.Column('matched_user_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matched_enrollment_id'], ['face_enrollments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matched_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_face_recognition_logs_device_id'), 'face_recognition_logs', ['device_id'], unique=False)
    op.create_index(op.f('ix_face_recognition_logs_id'), 'face_recognition_logs', ['id'], unique=False)
    op.create_index(op.f('ix_face_recognition_logs_matched_enrollment_id'), 'face_recognition_logs', ['matched_enrollment_id'], unique=False)
    op.create_index(op.f('ix_face_recognition_logs_matched_user_id'), 'face_recognition_logs', ['matched_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    op.drop_index(op.f('ix_face_recognition_logs_matched_user_id'), table_name='face_recognition_logs')
    op.drop_index(op.f('ix_face_recognition_logs_matched_enrollment_id'), table_name='face_recognition_logs')
    op.drop_index(op.f('ix_face_recognition_logs_id'), table_name='face_recognition_logs')
    op.drop_index(op.f('ix_face_recognition_logs_device_id'), table_name='face_recognition_logs')
    op.drop_table('face_recognition_logs')
    op.drop_index(op.f('ix_face_enrollments_user_id'), table_name='face_enrollments')
    op.drop_index(op.f('ix_face_enrollments_id'), table_name='face_enrollments')
    op.drop_index(op.f('ix_face_enrollments_device_id'), table_name='face_enrollments')
    op.drop_table('face_enrollments')
    op.drop_table('device_shares')
    op.drop_index(op.f('ix_device_schedules_device_id'), table_name='device_schedules')
    op.drop_table('device_schedules')
    op.drop_index(op.f('ix_device_logs_id'), table_name='device_logs')
    op.drop_index(op.f('ix_device_logs_created_at'), table_name='device_logs')
    op.drop_table('device_logs')
    op.drop_index(op.f('ix_devices_type'), table_name='devices')
    op.drop_index(op.f('ix_devices_search_keywords'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_dashboard_widgets_id'), table_name='dashboard_widgets')
    op.drop_index(op.f('ix_dashboard_widgets_dashboard_id'), table_name='dashboard_widgets')
    op.drop_table('dashboard_widgets')
    op.drop_table('invitation_keys')
    op.drop_table('hardware_nodes')
    op.drop_index(op.f('ix_dashboards_owner_id'), table_name='dashboards')
    op.drop_index(op.f('ix_dashboards_id'), table_name='dashboards')
    op.drop_table('dashboards')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
