"""cleanup_logs_and_hardware_relations

Revision ID: c7577f5b5776
Revises: b2e8f3a7c901
Create Date: 2026-04-22 11:03:23.431710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7577f5b5776'
down_revision: Union[str, Sequence[str], None] = 'b2e8f3a7c901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_logs_created_at'), table_name='device_logs')
    op.drop_index(op.f('ix_device_logs_id'), table_name='device_logs')
    op.drop_table('device_logs')
    op.drop_constraint(op.f('devices_hardwareId_fkey'), 'devices', type_='foreignkey')
    op.create_foreign_key(None, 'devices', 'hardware_nodes', ['hardware_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('hardware_nodes_owner_id_fkey'), 'hardware_nodes', type_='foreignkey')
    op.drop_column('hardware_nodes', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hardware_nodes', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('hardware_nodes_owner_id_fkey'), 'hardware_nodes', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.create_foreign_key(op.f('devices_hardwareId_fkey'), 'devices', 'hardware_nodes', ['hardware_id'], ['id'])
    op.create_table('device_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('device_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('actor', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('device_logs_device_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('device_logs_pkey'))
    )
    op.create_index(op.f('ix_device_logs_id'), 'device_logs', ['id'], unique=False)
    op.create_index(op.f('ix_device_logs_created_at'), 'device_logs', ['created_at'], unique=False)
    # ### end Alembic commands ###
